### PR TITLE
Readability and reduced repetition

### PR DESCRIPTION
**Pull request by Lordfirespeed**
Notable changes:
- update to reST docstrings (thank you, @tameTNT) 
- move the logic for 'restructuring cases' to its own method `balance()` (to be implemented as part of the task)
- use an `Enum` to identify which restructuring case is exhibited
- implement and use a `__replace` method to prevent repetition of transferring attributes from one node to another
- employ 'early return' technique to reduce indentation level and establish base cases
- Raise descriptive errors in cases that previously returned `None` or similar

### CODE REVIEW

**Comment by tameTNT** [comment]
I really just got this notification huh - just when @ksouthern is no longer a demonstrator 🥲
There was always going to be one eventually who did the great work 🫡

**Comment by Lordfirespeed** [comment]
> I really just got this notification huh - just when @ksouthern is no longer a demonstrator 🥲
> There was always going to be one eventually who did the great work 🫡

The ADS programming practical tasks for Epiphany term all still involve his repositories! 😂

**Comment by ksouthern** [comment]
I may not be a demonstrator any more, but I'll still go through the PR this weekend - there's a good chance this code will still be used next year.

**Comment by Lordfirespeed** [comment]
Bump :)

**Pull request merged**
